config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :blog_posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 get "my_stories" => "blog_posts#your_posts"

 root 'blog_posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
	  belongs_to :user
      has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
     belongs_to :user
	 belongs_to :blog_post
	 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :blog_posts
         has_many :comments
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

	def configure_permitted_parameters
   		devise_parameter_sanitizer.permit(:sign_up, keys: [:birthday, :name, :username])
		devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :username])
	end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]



  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  def your_posts
    @blog_posts = current_user.blog_posts 
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment = Comment.new
    @comment.blog_post_id = @blog_post.id
    @comment.user = current_user
    # @comment.entry="say here"

    @comments = @blog_post.comments
    # @blog_post_id = @blog_post_id.show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :category, :user_id, :blog_post_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]


  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :entry, :user_id, :blog_post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(blog_post) do |f| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>


  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, class: "form-control"%>

  </div>



  <div class="field">
    <%= f.label :blog_entry %>
    <%= f.text_area :blog_entry, class: "form-control"%>
  </div>  



  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category, class: "form-control"%>
  </div>


  
    <div class="field">
    <%= f.label :user_id %>
    <%= f.text_area :user_id,  class: "form-control"%>
  </div>



  <div class="actions">
  <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="right" title="Press it!">Submit</button>

</form>



<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Posts</h1>
<h2>There are <%=@blog_posts.count %> Blog Posts</h2>

<div class="row">
  <% @blog_posts.each do |blog_post| %>
    <div class="col-md-6">
       <div class="panel panel-info">
          <div class="panel-heading">
           <b><%= link_to blog_post.title, blog_post%></b>
          </div>
          <div class="panel-body">
          <b>by <%= blog_post.user.username %></b> <br>
           
             <%= blog_post.blog_entry[0..500] %>... [<%=link_to 'READ MORE', blog_post %>]
          </div>

        <% if current_user == blog_post.user %>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
            <%= link_to 'Destroy', blog_post, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
           </div>
        <% end %>
       </div>
    </div>
    <% end %>
    </div>
<br>


<%= link_to 'New Blog Post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">New Blog Post</h3>
  </div>
  <div class="panel-body">

<%= render 'form', blog_post: @blog_post %>



<button type="button" class="btn btn-default"><%= link_to 'Back', blog_posts_path %></button>


  </div>
</div>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
            <%= @blog_post.title %>

        </div>
        
        <div class="panel-body">
 		 <b>by <%= @blog_post.user.username %></b><br>
              <%= @blog_post.blog_entry %>
 				
        </div>
        <div class="panel-footer">

            <%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
            <%= link_to 'Back', blog_posts_path %>

        </div>
      </div>

	<%= render 'comments/form', comment: @comment %>

    <% @comments.each do |comment| %>
    <%= comment.entry %> by <%=comment.user.email%> <br>
    <% end %>


    </div>
</div>

app/views/blog_posts/your_posts.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Posts</h1>
<h2>There are <%=@blog_posts.count %> Blog Posts</h2>

<div class="row">
  <% @blog_posts.each do |blog_post| %>
    <div class="col-md-6">
       <div class="panel panel-info">
          <div class="panel-heading">
           <b><%= link_to blog_post.title, blog_post%></b>
          </div>
          <div class="panel-body">
          <b>by <%= blog_post.user.username %></b> <br>
           
             <%= blog_post.blog_entry[0..500] %>... [<%=link_to 'READ MORE', blog_post %>]
          </div>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
            <%= link_to 'Destroy', blog_post, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
       </div>
    </div>
    <% end %>
    </div>
<br>


<%= link_to 'New Blog Post', new_blog_post_path %>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>



  <div class="field">
    <%= f.label :entry %>
    <%= f.text_area :entry %>
  </div>

  <div class="field">
    <%= f.label :blog_post_id %>
    <%= f.text_area :blog_post_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_area :user_id %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-body">
<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @comment.entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Techtownblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"  %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" %>

  </head>
  <body>



        
     

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
   
      <a class="navbar-brand" href="#">Design Is My First Language</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "All Stories", root_path %></li>
      <li><%= link_to "My Stories", my_stories_path %></li>
      <li><%= link_to "Make a New Post", new_blog_post_path%></li>
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">

         <%if user_signed_in? %>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>

        <% elsif params[:controller] =="devise/registrations" && params[:action] == "new" %>
          <li><%= link_to "Log In",new_user_session_path %></li>
          <%else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
         <% end %>

  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



       



    <div class = "container" >
       <div class = "pull-right" >
       </div>
     <%= yield %>
     </div>
  </body>
</html>